version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.6.0
    working_directory: ~/repo

jobs:
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy_staging:
    executor: node
    steps:
      - checkout
      - run: scripts/deploy.sh staging

  deploy_dark_production:
    executor: node
    steps:
      - checkout
      - run: scripts/deploy.sh production

  flip_production:
    executor: node
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

  revert_production:
    executor: node
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - hold_production_deploy:
          type: approval
          requires:
            - deploy_staging
      - deploy_dark_production:
          requires:
            - hold_production_deploy
      - hold_flip_production:
          type: approval
          requires:
            - deploy_dark_production
      - flip_production:
          requires:
            - hold_flip_production
      - hold_revert_production:
          type: approval
          requires:
            - flip_production
      - revert_production:
          requires:
            - hold_revert_production
